routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'AgendaController@index');
Route::resource('/agenda', 'AgendaController', ['except' => ['index']]);

app/Agenda.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Agenda extends Model
{
    protected $fillable = ['nome', 'email', 'telefone', 'telefone2', 'facebook'];


}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/AgendaController.php
<?php

namespace App\Http\Controllers;

use App\Agenda;
use Illuminate\Http\Request;

use App\Http\Requests;

class AgendaController extends Controller
{

    private $agenda;

    public function __construct(Agenda $agenda)
    {
        $this->agenda = $agenda;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('agenda.list', ['contatos' => $this->agenda->all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('agenda.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $this->agenda->create($data);

        return redirect('/')->with(['msg' => 'Gravado com sucesso']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $contato = $this->agenda->find($id);
        return view('agenda.show', ['contato' => $contato]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $contato = $this->agenda->find($id);
        return view('agenda.edit', ['contato' => $contato]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/Agenda/add.blade.php
@extends('main.main')

@section('content')
    <div class="container">
        <form class="form-horizontal" action="{{route('store')}}" method="post">
            {{csrf_field()}}
            <div class="form-group">
                <div class="col-sm-12">
                    <label>Nome:</label>
                    <input class="form-control" type="text" name="nome">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-4">
                    <label>E-mail:</label>
                    <input class="form-control" type="text" name="email" id="">
                </div>
                <div class="col-sm-4">
                    <labele>Telefone Fixo</labele>
                    <input class="form-control" type="text" name="telefone" id="">
                </div>
                <div class="col-sm-4">
                    <labele>Celular:</labele>
                    <input class="form-control" type="text" name="telefone2" id="">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-12">
                    <label>Facebook</label>
                    <input class="form-control" type="text" name="facebook">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-12">
                    <input class="btn btn-block btn-success" type="submit" value="Salvar">
                </div>
            </div>
        </form>
    </div>
@stop

resources/views/Agenda/edit.blade.php
<div>
    <form class="form-horizontal" action="{{route('agenda.update', $contato->id)}}" method="post">
        {{csrf_field()}}
        {{method_field('PUT')}}
        <div class="form-group">
            <div class="col-sm-12">
                <label>Nome:</label>
                <input class="form-control" type="text" name="nome" value="{{$contato->nome}}">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-4">
                <label>E-mail:</label>
                <input class="form-control" type="text" name="email" value="{{$contato->email}}">
            </div>
            <div class="col-sm-4">
                <labele>Telefone Fixo</labele>
                <input class="form-control" type="text" name="telefone" value="{{$contato->telefone}}">
            </div>
            <div class="col-sm-4">
                <labele>Celular:</labele>
                <input class="form-control" type="text" name="telefone2" value="{{$contato->telefone2}}">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-12">
                <label>Facebook</label>
                <input class="form-control" type="text" name="facebook" value="{{$contato->facebook}}">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-12">
                <input class="btn btn-block btn-success" type="submit" value="Salvar">
            </div>
        </div>
    </form>
</div>

resources/views/Agenda/list.blade.php
@extends('main.main')

@section('content')
    <div class="container">
        @if(session('msg'))
            <span class="alert alert-success">
                {{session('msg')}}
            </span>
        @endif
    <table class="table table-bordered table-responsive">
        <thead>
            <th>Nome</th>
            <th>E-mail</th>
            <th>Ações</th>
        </thead>
        <tbody>
            @foreach($contatos as $contato)
                <tr>
                    <td>{{$contato->nome}}</td>
                    <td>{{$contato->email}}</td>
                    <td>
                        <a class="btn btn-info" href="{{route('agenda.show', $contato->id)}}">Detalhes</a>
                        <a class="btn btn-warning" href="javascript:$('#edit-contato').modal('show')" data-toggle="modal" data-target=".edit-{{$contato->id}}">Editar</a>
                        <a class="btn btn-danger" href="">remover</a>

                        <div class="modal fade edit-{{$contato->id}}" id="edit-contato">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-body">
                                        @include('agenda.edit')
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    </div>
@stop

resources/views/Agenda/show.blade.php
@extends('main.main')

@section('content')
    <div class="conatiner">
        <p><label>Nome</label> {{$contato->nome}}</p>
        <p><label>E-mail</label> {{$contato->email}}</p>
        <p><label>Telefone Fixo</label> {{$contato->telefone}}</p>
        <p><label>Celular</label> {{$contato->telefone2}}</p>
        <p><label>Facebook</label> {{$contato->facebook}}</p>
        <p><a class="btn btn-default" href="/">Voltar</a></p>
    </div>
@stop

resources/views/main/main.blade.php
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Agenda de contatos</title>
    <link rel="stylesheet" href="{{asset('bower_components/bootstrap/dist/css/bootstrap.min.css')}}">
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="navbar-header">
            <a href="#" class="navbar-brand">Agenda</a>
        </div>
    </nav>
    @yield('content')

    <script src="{{asset('bower_components/jquery/dist/jquery.min.js')}}"></script>
    <script src="{{asset('bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>

</body>
</html>